version: "3"

services: 
    app:
        build: .
        command: npm start
        ports: 
            - "3333:3333"
        volumes: 
            - .:/usr/app
    
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: "1234"
            PGDATA: /data/postgres
        volumes:
            - database-data:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped

volumes:
    database-data: